### ISSUE TITLE
readme.rst

### ISSUE THREAD

**Issue by plektra** [cloudgun/aws-auth-helper#1]
Missing README.rst is required for editable install of this tool (maybe missing due to .gitignore?):

```
lari@Laris-MacBook-Air ~/D/s/c/aws-auth-helper> pip install --editable .
Obtaining file:///Users/lari/Documents/src/cloudgun/aws-auth-helper
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/lari/Documents/src/cloudgun/aws-auth-helper/setup.py", line 5, in <module>
        long_description=open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/lari/Documents/src/cloudgun/aws-auth-helper
```

Adding empty README.rst fixed the installer issue.

**Comment by plektra** [comment]
Actually the application doesn't get installed to `~/.pyenv/versions/aws-auth-helper/lib/python2.7/site-packages/`

**Comment by plektra** [comment]
Could you include all dependencies to the install instructions?

```
lari@Laris-MacBook-Air ~/D/s/c/aws-auth-helper> make install
rm -rf dist build *.egg-info MANIFEST README.rst .tox .eggs
pandoc README.md -f markdown -t rst -s -o README.rst
make: pandoc: No such file or directory
make: *** [rst-readme] Error 1
```
